version: 2.1
jobs:
  compile:
   docker:
      - image: debian:trixie-slim
   steps:
      - run:
          shell: /bin/bash
          command: |
            apt update -y && apt upgrade -y && apt install -y sudo
            sudo apt install -y glibc-source git bc llvm lld inetutils python3 flex bison libc++ libxml2 python-pipx zip wget cpio jdk-openjdk tzdata
            sudo ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && date
            git clone --recursive --depth 1 https://github.com/sandatjepil/asus_kernel_sdm636.git -b codelinaro-eas kernel && cd kernel
            curl https://raw.githubusercontent.com/sandatjepil/cooking-kernel/zeus/build.sh > run.sh
            source run.sh
          no_output_timeout : 1h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
