version: 2.1
jobs:
  compile:
   docker:
      - image: wizardprjkt/build:kernel
   steps:
      - run:
          shell: /bin/bash
          command: |
            git clone --recursive --depth 1 https://github.com/LineageOS/android_kernel_asus_sdm660 -b lineage-20 kernel && cd kernel
            curl https://raw.githubusercontent.com/sandatjepil/cooking-kernel/noksu/build.sh > run.sh
            source run.sh
          no_output_timeout : 1h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
