version: 2.1
jobs:
  compile:
   docker:
      - image: wizardprjkt/build:kernel
   steps:
      - run:
          shell: /bin/bash
          command: |
            git clone --recursive --depth 1 https://github.com/sandatjepil/asus_kernel_sdm636 -b unstable kernel && cd kernel
            curl https://raw.githubusercontent.com/sandatjepil/cooking-kernel/circle/build.sh > run.sh
            source run.sh | tee -a error.log
          no_output_timeout : 1h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
