version: 2.1
jobs:
  compile:
    docker:
      - image: sandatjepil/build:jammy
    steps:
      - checkout
      - run:
          name: Kernel 4.14.x
          shell: /bin/bash
          command: |
            git clone -q --depth 1 -b 16 https://github.com/sandatjepil/kernel_xiaomi_sweet kernel
            bash build.sh
          no_output_timeout : 1h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile