version: 2.1
jobs:
  compile:
    docker:
      - image: ghcr.io/neutron-projects/docker-image:arch-neutron
    steps:
      - run:
          shell: /bin/bash
          command: |
            git clone -qb zeus --recursive --depth 15 https://github.com/sandatjepil/asus_kernel_sdm636.git kernel
            curl -sL https://raw.githubusercontent.com/sandatjepil/cooking-kernel/sky/build.sh | bash
          no_output_timeout : 1h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile