version: 2.1
jobs:
  compile:
    docker:
      - image: sandatjepil/build:kernel
    steps:
      - checkout
      - run:
          name: Masterpiece Creation
          shell: /bin/bash
          command: |
            bash build.sh
          no_output_timeout : 30m
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile