version: 2.1
jobs:
  compile:
   docker:
      - image: wizardprjkt/archlinux:latest
   steps:
      - run:
          shell: /bin/bash
          command: |
            sudo ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && date
            sudo pacman -Sy --noconfirm make
            # sudo pacman -Sy --noconfirm git bc llvm lld inetutils python3 flex bison libc++ libxml2 python-pipx zip wget cpio jdk-openjdk tzdata
            git clone --recursive --depth 1 https://github.com/sandatjepil/asus_kernel_sdm636 -b codelinaro-eas kernel && cd kernel
            curl https://raw.githubusercontent.com/sandatjepil/cooking-kernel/circle/build.sh > run.sh
            source run.sh
          no_output_timeout : 1h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
