version: 2.1
jobs:
  compile:
   docker:
      - image: sandatjepil/build:kernel
   steps:
      - run:
          command: |
            git clone --recursive https://github.com/sandatjepil/asus_kernel_sdm636 -b unstable kernel && cd kernel
            curl https://raw.githubusercontent.com/sandatjepil/cooking-kernel/circle/build.sh > run.sh
            source run.sh
          no_output_timeout : 5h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
